# Git aliases
alias gs='git status'
alias ga='git add'
alias gaa='git add .'
alias gb='git branch'
alias gbn='git checkout -b'  # new branch
alias gc='git commit'
alias gcm='git commit -m'
alias gco='git checkout'
alias gd='git diff'
alias gl='git log --oneline'
alias gp='git push'
alias gpf='git push --force'
alias gpl='git pull'
alias gm='git merge'
alias grb='git rebase'
alias grs='git reset'
alias grh='git reset --hard'
alias gst='git stash'
alias gstp='git stash pop'
alias gundo='git reset --soft HEAD~1'  # undo last commit
alias gclean='git clean -fd'  # remove untracked files/directories 